server:
  port: 5000
  servlet:
    context-path: /uaa
spring:
  data:
    mongodb:
      host: localhost
      database: user
      port: 27017
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
