server:
  port: 8001
spring:
  data:
    mongodb:
      host: localhost
      database: table
      port: 27017
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/